---

- name: ensure .gitignore exists
  file:
    state=touch
    path={{ genesis_deploy_dir }}/../.gitignore

- name: create - ensure .gitignore is correct
  lineinfile: 
    dest={{ genesis_deploy_dir }}/../.gitignore
    line={{ item }}
  with_items:
    - "**/terraform.tfvars"
    - "**/bootstrap"
    - "**/destroy"
    - "**/provision/**"

- name: setup - create bootstrap folder
  file:
    state=directory
    path={{ genesis_deploy_dir }}/
    mode=770

- name: move setup files
  copy:
    src=provision/
    dest={{ genesis_deploy_dir }}/
    mode=660

- name: create - generate terraform tfvars file
  template:
    src=terraform.tfvars.j2
    dest={{ genesis_deploy_dir }}/terraform.tfvars
    mode=660

- name: create - generate bootstrap file
  template:
    src=bootstrap.j2
    dest={{ genesis_deploy_dir }}/bootstrap
    mode=750

- name: generate destroy file
  template:
    src=destroy.j2
    dest={{ genesis_deploy_dir }}/destroy
    mode=750

- name: link terraform file
  file:
    state=link
    src={{ genesis_terraform_file }}
    dest={{ genesis_deploy_dir }}/genesis.tf

