---

- name: ensure .gitignore exists
  file:
    state=touch
    path={{ genesis_deploy_dir }}/.gitignore

- name: create - ensure .gitignore is correct
  lineinfile: 
    dest={{ genesis_deploy_dir }}/.gitignore
    line={{ item }}
  with_items:
    - "**/terraform.tfvars"
    - "**/bootstrap"
    - "**/destroy"
    - "**/provision/**"

- name: setup - create bootstrap folder
  file:
    state=directory
    path={{ genesis_deploy_dir }}/provision
    mode=660

- name: move setup files
  copy:
    src=provision/
    dest={{ genesis_deploy_dir }}/provision/
    mode=660

- name: create - generate terraform tfvars file
  template:
    src=terraform.tfvars.j2
    dest={{ genesis_deploy_dir }}/provision/terraform.tfvars
    mode=660

- name: create - generate bootstrap file
  template:
    src=bootstrap.j2
    dest={{ genesis_deploy_dir }}/provision/bootstrap
    mode=750

- name: generate destroy file
  template:
    src=destroy.j2
    dest={{ genesis_deploy_dir }}/provision/destroy
    mode=750


